// Code generated by goctl. DO NOT EDIT.
// Source: account_api.proto

package server

import (
	"context"

	"github.com/groupargit/casacoloraccount-grpc/rpc/internal/logic"
	"github.com/groupargit/casacoloraccount-grpc/rpc/internal/svc"
	"github.com/groupargit/casacoloraccount-grpc/rpc/types/account/v1alpha1"
)

type AccountAPIServiceServer struct {
	svcCtx *svc.ServiceContext
	v1alpha1.UnimplementedAccountAPIServiceServer
}

func NewAccountAPIServiceServer(svcCtx *svc.ServiceContext) *AccountAPIServiceServer {
	return &AccountAPIServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountAPIServiceServer) Login(ctx context.Context, in *v1alpha1.AccountLoginRequest) (*v1alpha1.AccountLoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
