// Code generated by goctl. DO NOT EDIT.
// Source: account_api.proto

package accountapiservice

import (
	"context"

	"github.com/groupargit/casacoloraccount-grpc/rpc/types/account/v1alpha1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountLoginRequest  = v1alpha1.AccountLoginRequest
	AccountLoginResponse = v1alpha1.AccountLoginResponse
	User                 = v1alpha1.User

	AccountAPIService interface {
		Login(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error)
	}

	defaultAccountAPIService struct {
		cli zrpc.Client
	}
)

func NewAccountAPIService(cli zrpc.Client) AccountAPIService {
	return &defaultAccountAPIService{
		cli: cli,
	}
}

func (m *defaultAccountAPIService) Login(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error) {
	client := v1alpha1.NewAccountAPIServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
