// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: account_api.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AccountAPIService_Login_FullMethodName = "/account.v1alpha1.AccountAPIService/Login"
)

// AccountAPIServiceClient is the client API for AccountAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountAPIServiceClient interface {
	Login(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error)
}

type accountAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountAPIServiceClient(cc grpc.ClientConnInterface) AccountAPIServiceClient {
	return &accountAPIServiceClient{cc}
}

func (c *accountAPIServiceClient) Login(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error) {
	out := new(AccountLoginResponse)
	err := c.cc.Invoke(ctx, AccountAPIService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAPIServiceServer is the server API for AccountAPIService service.
// All implementations must embed UnimplementedAccountAPIServiceServer
// for forward compatibility
type AccountAPIServiceServer interface {
	Login(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error)
	mustEmbedUnimplementedAccountAPIServiceServer()
}

// UnimplementedAccountAPIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountAPIServiceServer struct {
}

func (UnimplementedAccountAPIServiceServer) Login(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccountAPIServiceServer) mustEmbedUnimplementedAccountAPIServiceServer() {}

// UnsafeAccountAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountAPIServiceServer will
// result in compilation errors.
type UnsafeAccountAPIServiceServer interface {
	mustEmbedUnimplementedAccountAPIServiceServer()
}

func RegisterAccountAPIServiceServer(s grpc.ServiceRegistrar, srv AccountAPIServiceServer) {
	s.RegisterService(&AccountAPIService_ServiceDesc, srv)
}

func _AccountAPIService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountAPIService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServiceServer).Login(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountAPIService_ServiceDesc is the grpc.ServiceDesc for AccountAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.v1alpha1.AccountAPIService",
	HandlerType: (*AccountAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccountAPIService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_api.proto",
}
